### ISSUE TITLE
Wrong formatting on html

### ISSUE THREAD

**Issue by AntonioCS** [Kotlin/kotlin-by-example#106]
On page: https://play.kotlinlang.org/byExample/08_productivity_boosters/04_Smart%20Casts
This is what I see:

![image](https://user-images.githubusercontent.com/1086401/79064420-ad295480-7ca0-11ea-8a0b-30a4d4d70a8a.png)

Notice how the items (1 and 2) are no in a separate line like they are in the markdown page:

![image](https://user-images.githubusercontent.com/1086401/79064436-d34ef480-7ca0-11ea-99a8-3a848ac1df25.png)

I am on Windows 10 pro using Firefox 74.0.1

**Comment by p7nov** [comment]
Thanks! Fixed this.
