### ISSUE TITLE
Example in 09_Kotlin_JS/05_Canvas produces errors

### ISSUE THREAD

**Issue by blueglyph** [Kotlin/kotlin-by-example#116]
This code

```kotlin
CanvasState(canvas).apply {
    addShape(Kotlin)
    addShape(Creature(size * 0.25, this))
    addShape(Creature(size * 0.75, this))
}
```
 
returns the following errors when run on the page:

> Using 'jq(Element): JQuery' is an error. Use declarations from 'https://bintray.com/kotlin/js-externals/kotlin-js-jquery' package instead.
> Using 'jq(Element): JQuery' is an error. Use declarations from 'https://bintray.com/kotlin/js-externals/kotlin-js-jquery' package instead.
> Using 'jq(Element): JQuery' is an error. Use declarations from 'https://bintray.com/kotlin/js-externals/kotlin-js-jquery' package instead.
> Using 'jq(Element): JQuery' is an error. Use declarations from 'https://bintray.com/kotlin/js-externals/kotlin-js-jquery' package instead.
> Using 'MouseEvent' is an error. Use declarations from 'https://bintray.com/kotlin/js-externals/kotlin-js-jquery' package instead.

Tested on 

- Chrome Version 85.0.4183.121 (Official Build) (64-bit), on Windows 7 x64 pro
- Microsoft Edge Version 85.0.564.63 (Official build) (64-bit), same platform

**Comment by SebastianAigner** [comment]
Fixed by merging #118, thanks for reporting this! 👍  Feel free to open more tickets if you run into any additional issues!
