### ISSUE TITLE
HTML Builder example produces deprecation warning and is not aligned with Type Safe Builders reference doc

### ISSUE THREAD

**Issue by VasylTretiakov** [Kotlin/kotlin-by-example#123]
Running the **HTML Builder** example code in the https://play.kotlinlang.org/byExample/09_Kotlin_JS/06_HtmlBuilder page produces the expected result while displaying deprecation warnings next to several lines (please refer to the screenshot below).

![kotlin example warnings](https://user-images.githubusercontent.com/3999712/97361146-d067ca00-18a7-11eb-9f5e-ae285107ac88.png)

Attempt to run the code in _Kotlin Playground_ fails with errors (please refer to the screenshot below).

![kotlin playground errors](https://user-images.githubusercontent.com/3999712/97361147-d1006080-18a7-11eb-9926-6e2be5c25907.png)

The **Type Sage Builders** reference doc mentioned at the bottom of the page contains a different implementation that [after minor adaptations] runs successfully in _Kotlin Playground_.

It seems beneficial to align **HTML Builder** example with with **Type Safe Builders** reference doc and make it executable in Kotlin Playground.

**Comment by p7nov** [comment]
Fixed in PR #124  by @VasylTretiakov.
