### ISSUE TITLE
Adding user-friendly examples for getting started with K/N

### ISSUE THREAD

**Issue by Hamzantal** [Kotlin/kotlin-by-example#86]
Kotlin native is not the most beginner friendly tool out there at the moment. Maybe a suggestion for chapter 10 can be focused on some examples with full projects (Including buildscripts, def files, etc)? Multiple files? Maybe that might be undoable, but I think we should try.

Examples can be for all three platforms (Mingw, MacOs, and Linux)? 

We can also add some examples for WebAssembly, and Swift porting?
This can be a great way for people to learn how to use libraries and such with Kotlin Native, and such a project allows us to cover many different kinds of projects. 

Of course, we don't have to focus on the *building* part of things, we can also focus on creating examples for memory management, etc.

**Comment by Hamzantal** [comment]
If some maintainer/contributer thinks this is a good idea, I will start writing some articles =D

**Comment by AlexanderPrendota** [comment]
Hello! Try [`hands-on`](https://play.kotlinlang.org/hands-on/overview) =)

**Comment by Hamzantal** [comment]
Sweet. This is a very helpful resource! I did not know that existed.

*Best,*
*Hamza*

**Comment by Hamzantal** [comment]
Closing due to the presence of [hands-on](https://play.kotlinlang.org/hands-on/overview)

**Comment by AlexanderPrendota** [comment]
Hey @Hamzantal ! Thank you for your question) 
no-no we are glad to see your examples =) It's a really good idea.

You can submit a PR here or in [hands-on](https://github.com/kotlin-hands-on) :) 

If you have any questions feel free to contact me.

**Comment by Hamzantal** [comment]
Got it. Thank you. I will see how I can write examples of CPointers
